apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: some-microservice
  name: some-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: some-microservice
  template:
    metadata:
      labels:
        app: some-microservice
    spec:
      containers:
      - image: joellubi/k8s-chain-of-failure-server
        name: k8s-chain-of-failure-server
        env:
        - name: AVERAGE_REQUESTS_UNTIL_FAILURE
          value: "10"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: some-microservice
  name: some-microservice
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: some-microservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: load-generator
  name: load-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - image: joellubi/k8s-chain-of-failure-load-generator
        name: k8s-chain-of-failure-load-generator
        env:
        - name: REQUESTS_PER_MINUTE
          value: "10"